name: Update Message

on:
  issues:
    types: [opened]

jobs:
  update-message:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Update Message
      - name: Update Message
        run: |
          SANITIZED=`echo '${{github.event.issue.title}}'' | tr -d '"'`
          echo "message = \"${SANITIZED}\";" >> message.js

      # Add, commit, and push changes
      - name: Add changes and push to deployment
        run: |
          git config --global user.name "Keo222"
          git config --global user.email "kyle.olsen222@gmail.com"
          git add message.js
          git commit -m "${{ github.actor }} updated message"
          git push
